name: Build lsfg-vk FlatpakUI

on:
  workflow_dispatch:
  push:
    branches: ["release"]

jobs:
  flatpak:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["24.08"]
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-${{ matrix.version }}
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Flatpak extension (${{ matrix.version }})
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: "gay.pancake.lsfg-vk-ui.flatpak"
          manifest-path: "scripts/flatpak/gay.pancake.lsfg-vk-ui.yml"
          verbose: true
